//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrejchenko.LabTwo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrejchenko.LabOne.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СО ЕЭС
        ///ФСК ЕЭС
        ///НИИ ТПУ
        ///НИИ ТГУ
        ///Google corp.
        ///Yandex corp.
        ///.
        /// </summary>
        internal static string CompanyNames {
            get {
                return ResourceManager.GetString("CompanyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юлия
        ///Анна
        ///Василия
        ///Александра
        ///Елена
        ///Ирина
        ///.
        /// </summary>
        internal static string FirstName_Female {
            get {
                return ResourceManager.GetString("FirstName_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кирилл
        ///Андрей
        ///Василий
        ///Георгий
        ///Сергей
        ///Александр
        ///Дмитрий
        ///Картизол
        ///.
        /// </summary>
        internal static string FirstName_Male {
            get {
                return ResourceManager.GetString("FirstName_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Евреева
        ///Галгеева
        ///Малеева
        ///Трундяк
        ///Фридрихна
        ///.
        /// </summary>
        internal static string LastName_Female {
            get {
                return ResourceManager.GetString("LastName_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гришенко
        ///Борисов
        ///Андреев
        ///Танатьев
        ///Филейченко
        ///.
        /// </summary>
        internal static string LastName_Male {
            get {
                return ResourceManager.GetString("LastName_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МБОУ СОШ N22
        ///МБОУ СОШ N21
        ///МБОУ СОШ N3
        ///Детский Сад N1
        ///Детский Сад N2
        ///Детский Сад N10
        ///.
        /// </summary>
        internal static string PlaceOfTeachChild {
            get {
                return ResourceManager.GetString("PlaceOfTeachChild", resourceCulture);
            }
        }
    }
}
